FROM oraclelinux:8-slim

LABEL version="3.7.0"
LABEL description="TOTVS LicenseServer" 
LABEL maintainer="Julian de Almeida Santos <julian.santos.info@gmail.com>"

ENV LICENSE_TCP_PORT=2234
ENV LICENSE_CONSOLEFILE=/totvs/licenseserver/bin/appserver/licenseserver.log
ENV LICENSE_PORT=5555
ENV LICENSE_WEBAPP_PORT=8020
ENV DEBUG_SCRIPT=false
ENV TZ=America/Sao_Paulo

COPY ./totvs /totvs
COPY ./entrypoint.sh /entrypoint.sh
COPY ./healthcheck.sh /healthcheck.sh

RUN chmod +x /entrypoint.sh /healthcheck.sh

ENTRYPOINT [ "/entrypoint.sh" ]

EXPOSE 2234 4000 5555 8020