FROM redhat/ubi8:8.5-236

LABEL release="3.9.0.4558336"
LABEL description="TOTVS SmartView Server" 
LABEL maintainer="Julian de Almeida Santos <julian.santos.info@gmail.com>"

ENV EXTRACT_RESOURCES=true
ENV DEBUG_SCRIPT=false
ENV TZ=America/Sao_Paulo

COPY ./totvs /totvs

WORKDIR /totvs

# Atualização e instalação de dependências
# 1. oracle-epel-release-el8: Necessário para o libgdiplus
# 2. fontconfig: Essencial para o SkiaSharp gerenciar fontes
# 3. libgdiplus: Necessário para compatibilidade System.Drawing/DevExpress
RUN PKG_MGR=$(command -v dnf || command -v microdnf) && \
    $PKG_MGR update -y && \
    # Instalação do EPEL
    if command -v dnf > /dev/null 2>&1; then \
        $PKG_MGR install -y https://dl.fedoraproject.org/pub/epel/epel-release-latest-8.noarch.rpm; \
    else \
        # No Oracle Linux Slim, o builder é necessário para dependências da libgdiplus
        $PKG_MGR install -y oracle-epel-release-el8; \
    fi && \
    # Instalação de pacotes
    $PKG_MGR install -y \
        gzip \
        iputils \
        nano \
        procps-ng \
        libicu \
        fontconfig \
        libX11 \
        libgdiplus && \
    # Limpeza completa
    $PKG_MGR clean all && \
    rm -rf /var/cache/dnf /var/cache/yum /var/lib/dnf/history

# Garante que o cache de fontes seja gerado (evita erro de TypeInitialization no Skia)
RUN fc-cache -fv

COPY ./entrypoint.sh /entrypoint.sh
COPY ./healthcheck.sh /healthcheck.sh

RUN chmod +x /entrypoint.sh /healthcheck.sh

ENTRYPOINT [ "/entrypoint.sh" ]

EXPOSE 7017 7019