FROM juliansantosinfo/oracle_xe:21.3.0

LABEL version="21.3.0"
LABEL description="TOTVS Oracle"
LABEL maintainer="Julian de Almeida Santos <julian.santos.info@gmail.com>"

ENV ORACLE_SID=XE
ENV ORACLE_PWD=ProtheusDatabasePassword1
ENV ORACLE_CHARACTERSET=WE8MSWIN1252
ENV RESTORE_BACKUP=Y
ENV DEBUG_SCRIPT=false
ENV TZ=America/Sao_Paulo

COPY ./resources/data.tar.gz /tmp/data.tar.gz
COPY entrypoint.sh /entrypoint.sh
COPY healthcheck.sh /healthcheck.sh

USER root

RUN chown oracle:oinstall /entrypoint.sh /healthcheck.sh /tmp/data.tar.gz
RUN chmod +x /entrypoint.sh /healthcheck.sh

USER oracle

EXPOSE 1521

ENTRYPOINT [ "/entrypoint.sh" ]
