FROM oraclelinux:8-slim

LABEL version="24.1.1.0"
LABEL description="TOTVS DBAccess" 
LABEL maintainer="Julian de Almeida Santos <julian.santos.info@gmail.com>"

ENV DATABASE_PROFILE=
ENV DATABASE_SERVER=
ENV DATABASE_PORT=
ENV DATABASE_ALIAS=protheus
ENV DATABASE_NAME=protheus
ENV DATABASE_USERNAME=
ENV DATABASE_PASSWORD=
ENV DATABASE_WAIT_RETRIES=30
ENV DATABASE_WAIT_INTERVAL=2
ENV DBACCESS_LICENSE_SERVER=totvs_licenseserver
ENV DBACCESS_LICENSE_PORT=5555
ENV LICENSE_WAIT_RETRIES=30
ENV LICENSE_WAIT_INTERVAL=2
ENV DEBUG_SCRIPT=false
ENV DBACCESS_CONSOLEFILE=/totvs/dbaccess/multi/dbconsole.log
ENV TZ=America/Sao_Paulo

COPY ./totvs /totvs
COPY ./entrypoint.sh /entrypoint.sh
COPY ./setup-build.sh /setup-build.sh
COPY ./setup-database.sh /setup-database.sh
COPY ./setup-dbaccess.sh /setup-dbaccess.sh

WORKDIR /totvs

RUN chmod +x /entrypoint.sh /setup-build.sh /setup-database.sh /setup-dbaccess.sh \
    && /setup-build.sh

ENTRYPOINT [ "/entrypoint.sh" ]

EXPOSE 7890 7891