# Imagem base oficial do SQL Server 2019
FROM mcr.microsoft.com/mssql/server:2019-CU32-GDR3-ubuntu-20.04

LABEL version="12.1.2510"
LABEL description="TOTVS MSSQL" 
LABEL maintainer="Julian de Almeida Santos <julian.santos.info@gmail.com>"

USER root

# Variáveis obrigatórias de configuração do SQL Server
ENV ACCEPT_EULA=Y
ENV SA_PASSWORD=ProtheusDatabasePassword1
ENV RESTORE_BACKUP=Y
ENV DEBUG_SCRIPT=false
ENV TZ=America/Sao_Paulo

# Copiar o backup compactado para dentro da imagem
COPY ./resources/data.tar.gz /tmp/data.tar.gz
COPY entrypoint.sh /entrypoint.sh

# Ajustar permissões para entrypoint.sh
RUN chown -R root:root /entrypoint.sh && \
    chmod -R 770 /entrypoint.sh

USER mssql

# Expor a porta padrão
EXPOSE 1433

# Comando padrão para iniciar o SQL Server
CMD ["/entrypoint.sh"]
