# Imagem base oficial do SQL Server 2019
FROM mcr.microsoft.com/mssql/server:2019-CU32-GDR3-ubuntu-20.04

LABEL version="12.1.2410"
LABEL description="TOTVS MSSQL" 
LABEL maintainer="Julian de Almeida Santos <julian.santos.info@gmail.com>"

USER root

ENV ACCEPT_EULA=Y
ENV SA_PASSWORD=ProtheusDatabasePassword1
ENV RESTORE_BACKUP=Y
ENV DEBUG_SCRIPT=false
ENV TZ=America/Sao_Paulo

COPY ./resources/data.tar.gz /tmp/data.tar.gz
COPY entrypoint.sh /entrypoint.sh
COPY healthcheck.sh /healthcheck.sh

RUN chown -R mssql:root /entrypoint.sh /healthcheck.sh && \
    chmod -R 770 /entrypoint.sh /healthcheck.sh

USER mssql

EXPOSE 1433

CMD ["/entrypoint.sh"]
